### ISSUE TITLE
Composing enums with @inaccessible tag in two subgraphs fail with wrong @repeatable check

### ISSUE THREAD

**Issue by jiajun-brex** [wundergraph/cosmo#765]
### Component(s)

composition

### Component version

0.22

### wgc version

NA

### controlplane version

NA

### router version

NA

## Description
Composing two subgraphs with enums with inaccessible tag failed with wrong @repeatble check error

## Steps to Reproduce
Adding these two subgraphs to inaccessible.test.ts, it should succeed, however it failed
```

test('that there should be no error composing two enum fields with @inaccessible across subgraphs', () => {
  const { errors } = federateSubgraphs([subgraphEnum1, subgraphEnum2]);
  // console.log(errors)
  expect(errors).toBeUndefined();
});
  
const subgraphEnum1: Subgraph = {
name: 'subgraph-enum1',
url: '',
definitions: parse(`
  type Query {
    entity: String
  }

  enum TestEnum {
    A
    B @inaccessible
  }
`),
};

const subgraphEnum2: Subgraph = {
name: 'subgraph-enum2',
url: '',
definitions: parse(`
enum TestEnum {
  A
  B @inaccessible
}
`),
```
## Expected Result
Composition success

## Actual Result
Error, the repeatable should not check across subgraphs?

```
[
  Error: The definition for the directive "inaccessible" does not define it as repeatable, but the directive has been declared on more than one instance of the type "B".
      at Module.invalidRepeatedFederatedDirectiveErrorMessage (/Users/jiajun.zhao/cosmo/composition/src/errors/errors.ts:269:10)
      at getValidFlattenedPersistedDirectiveNodeArray (/Users/jiajun.zhao/cosmo/composition/src/schema-building/utils.ts:1902:19)
      at getPersistedDirectiveNodes (/Users/jiajun.zhao/cosmo/composition/src/schema-building/utils.ts:1920:8)
      at Module.getNodeWithPersistedDirectivesByData (/Users/jiajun.zhao/cosmo/composition/src/schema-building/utils.ts:1937:26)
      at FederationFactory.federate (/Users/jiajun.zhao/cosmo/composition/src/federation/federation-factory.ts:949:35)
      at Module.federateSubgraphs (/Users/jiajun.zhao/cosmo/composition/src/federation/federation-factory.ts:1382:5)
      at /Users/jiajun.zhao/cosmo/composition/tests/inaccessible.test.ts:161:24
      at file:///Users/jiajun.zhao/cosmo/composition/node_modules/@vitest/runner/dist/index.js:135:14
      at file:///Users/jiajun.zhao/cosmo/composition/node_modules/@vitest/runner/dist/index.js:60:26
      at runTest (file:///Users/jiajun.zhao/cosmo/composition/node_modules/@vitest/runner/dist/index.js:771:17)
]
```

### Environment information

NA

### Additional context

Seems the repeatable check is wrongly applied across subgraphs. We observe this issue after this pr https://github.com/wundergraph/cosmo/pull/595

**Comment by Aenimus** [comment]
Hi @jiajun-brex,

This is fixed with the following minimums:
[wgc@0.53.0](https://github.com/wundergraph/cosmo/compare/wgc@0.52.1...wgc@0.53.0)
[router@0.85.0](https://github.com/wundergraph/cosmo/compare/router@0.84.5...router@0.85.0)
[controlplane@0.85.0](https://github.com/wundergraph/cosmo/compare/controlplane@0.84.2...controlplane@0.85.0)

Thanks for the report!
