### ISSUE TITLE
Trying to delete a federated graph raises an error

### ISSUE THREAD

**Issue by maxrad82** [wundergraph/cosmo#895]
### Component(s)

cli

### Component version

latest

### wgc version

latest

### controlplane version

latest

### router version

latest

## Description

When trying to delete a federated graph, an error occurs. Other federated commands works. API KEY and API URL are correctly set

## Steps to Reproduce

npx wgc federated-graph delete GRAPH-NAME

## Expected Result

Should delete the federated

## Actual Result

An error is raised

## Environment
OS: (e.g., "Ubuntu 20.04")
Package Manager: pnpm, npm, yarn, etc
Compiler(if manually compiled): (e.g., "go 14.2")

### Log output

```shell
{"type":"S3ServiceException","message":"The Access Key Id you provided does not exist in our records.","stack":"InvalidAccessKeyId: The Access Key Id you provided does not exist in our records.\n    at throwDefaultError (/app/node_modules/.pnpm/@smithy+smithy-client@2.4.2/node_modules/@smithy/smithy-client/dist-cjs/index.js:838:20)\n    at /app/node_modules/.pnpm/@smithy+smithy-client@2.4.2/node_modules/@smithy/smithy-client/dist-cjs/index.js:847:5\n    at de_CommandError (/app/node_modules/.pnpm/@aws-sdk+client-s3@3.529.1/node_modules/@aws-sdk/client-s3/dist-cjs/index.js:4756:14)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async /app/node_modules/.pnpm/@smithy+middleware-serde@2.1.3/node_modules/@smithy/middleware-serde/dist-cjs/index.js:35:20\n    at async /app/node_modules/.pnpm/@aws-sdk+middleware-signing@3.523.0/node_modules/@aws-sdk/middleware-signing/dist-cjs/index.js:192:18\n    at async /app/node_modules/.pnpm/@smithy+middleware-retry@2.1.4/node_modules/@smithy/middleware-retry/dist-cjs/index.js:320:38\n    at async /app/node_modules/.pnpm/@aws-sdk+middleware-sdk-s3@3.525.0/node_modules/@aws-sdk/middleware-sdk-s3/dist-cjs/index.js:97:20\n    at async /app/node_modules/.pnpm/@aws-sdk+middleware-sdk-s3@3.525.0/node_modules/@aws-sdk/middleware-sdk-s3/dist-cjs/index.js:120:14\n    at async /app/node_modules/.pnpm/@aws-sdk+middleware-logger@3.523.0/node_modules/@aws-sdk/middleware-logger/dist-cjs/index.js:33:22","name":"InvalidAccessKeyId","$fault":"client","$metadata":{"httpStatusCode":403,"requestId":"17DC90321B4617BE","attempts":1,"totalRetryDelay":0},"Code":"InvalidAccessKeyId","BucketName":"cosmo","Resource":"/cosmo/","RequestId":"17DC90321B4617BE","HostId":"1767b1a2-81d3-44e4-a99d-5178d69bfd55"},"msg":"The Access Key Id you provided does not exist in our records."}
```

**Comment by maxrad82** [comment]
Nevermind, this is due to the user access permission within minio, not the apiKey.
